# Generated by Django 5.1.1 on 2024-09-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
